feat: Fetch epoch info from the RewardDistribution contract
paraswap/paraswap-volume-tracker pull request #3
Opened 2021-12-02 12:14 UTC by nduchak

2021-12-29 10:28 UTC, ColonelJ requested changes
Part of the information for each epoch is stored on chain, including the number of epochs and calc timestamps and send blocknumber/timestamps for each epoch.  Some of this info is required (calc timestamp), and anyway it might be better for the full node if you search for the event only on the individual blocks where they occur rather than a large range of blocks.  Somehow there needs to be a check that you got the events for all the epochs you expect.  Also the `CurrentEpoch` in `StakingSettings` can probably be set based on the number of epochs read from the SC.

2021-12-29 10:28 UTC, ColonelJ commented on src/lib/epoch-info.ts
> +        calcTimeStamp: 1,
The calcTimeStamp is stored on chain and needs to be retrieved for each epoch.

2021-12-29 11:33 UTC, shresthagrawal commented
I agree with Jason's comments! You can follow the following sequence: 
1. Fetch the currentEpoch
2. For each epoch index before the currentEpoch
    1. Fetch the epochHistory[i] to get sendBlockNumber, and calcTimestamp
    2. Use sendBlockNumber to fetch for exact event 
    3. Set the all the info about the epoch
    - If anything in this level fails log an error, retry n times and finally throw an error
- if you get any error simply catch, log and process.exit

2021-12-29 13:45 UTC, ColonelJ requested changes
You still need to update `CurrentEpoch` in `StakingSettings`.

2022-01-04 21:06 UTC, ColonelJ approved these changes

2022-01-05 05:52 UTC, merged